tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "secondary": "#46617b",
                    "secondary-container": "#c4e0fe",
                    "surface-variant": "#d8e3fb",
                    "on-tertiary": "#ffffff",
                    "tertiary-fixed-dim": "#ffb59b",
                    "on-primary-fixed-variant": "#0040a2",
                    "on-tertiary-fixed": "#380d00",
                    "on-error": "#ffffff",
                    "surface-container-low": "#f0f3ff",
                    "on-primary-fixed": "#001848",
                    "surface-container": "#e7eeff",
                    "tertiary-container": "#a33500",
                    "on-primary-container": "#c4d2ff",
                    "surface-bright": "#f9f9ff",
                    "surface-tint": "#0c56d0",
                    "on-error-container": "#93000a",
                    "primary-fixed": "#dae2ff",
                    "secondary-fixed-dim": "#aec9e7",
                    "tertiary": "#7b2600",
                    "on-background": "#111c2d",
                    "on-tertiary-container": "#ffc6b2",
                    "secondary-fixed": "#cee5ff",
                    "on-surface-variant": "#434654",
                    "outline": "#737685",
                    "error-container": "#ffdad6",
                    "surface-container-lowest": "#ffffff",
                    "surface-dim": "#cfdaf2",
                    "inverse-primary": "#b2c5ff",
                    "on-secondary-fixed-variant": "#2e4962",
                    "primary-container": "#0052cc",
                    "background": "#f9f9ff",
                    "on-primary": "#ffffff",
                    "on-secondary-container": "#48637d",
                    "on-secondary-fixed": "#001d32",
                    "primary-fixed-dim": "#b2c5ff",
                    "surface-container-highest": "#d8e3fb",
                    "primary": "#003d9b",
                    "surface": "#f9f9ff",
                    "surface-container-high": "#dee8ff",
                    "on-tertiary-fixed-variant": "#812800",
                    "outline-variant": "#c3c6d6",
                    "tertiary-fixed": "#ffdbcf",
                    "inverse-surface": "#263143",
                    "error": "#ba1a1a",
                    "inverse-on-surface": "#ecf1ff",
                    "on-secondary": "#ffffff",
                    "on-surface": "#111c2d"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "sidebar-width": "260px",
                    "stack-lg": "1.5rem",
                    "gutter": "1.5rem",
                    "section-padding": "2rem",
                    "stack-md": "1rem",
                    "container-max-width": "1280px",
                    "stack-sm": "0.5rem"
            },
            "maxWidth": {
                    "container-max-width": "1280px"
            },
            "fontFamily": {
                    "label-md": ["Inter"],
                    "display-lg": ["Inter"],
                    "label-sm": ["Inter"],
                    "title-md": ["Inter"],
                    "body-lg": ["Inter"],
                    "body-md": ["Inter"],
                    "display-md": ["Inter"],
                    "title-lg": ["Inter"]
            },
            "fontSize": {
                    "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
                    "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                    "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "display-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                    "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
            }
          },
        },
      }